### ISSUE TITLE
-template only posts the last argument

### ISSUE THREAD

**Issue by MCOfficer** [MCOfficer/EndlessSky-Discord-Bot#25]
when calling -template with multiple arguments (such as `-template plugin outfit`), only the latter argument will be processed (only the outfit template gets sent).

**Comment by tehhowch** [comment]
should be fixed by #26 
Not on my *nix box so I can't test it.

The issue was mostly braces - you need them for multiple blocks. E.g. the original code would for-loop over the arguments, but the sendmessage command was in a different execution block than the if(.....)else block. Unlike python, the indent level (e.g. whitespace) does not alter the interpretation of code in java/c++
