### ISSUE TITLE
add governments to lookups

### ISSUE THREAD

**Issue by MCOfficer** [MCOfficer/EndlessSky-Discord-Bot#34]
either as lookup or as separate -government, cause peeps keep asking.
rn -showdata X only brings up the respective phrase for the ship names.

**Comment by tehhowch** [comment]
I would make it a part of showdata

This should be as simple as adding `"government"` to the array that gets used in checklookup

**Comment by tehhowch** [comment]
It's already there, so it should be working.
![screenshot_2017-08-09-06-30-42](https://user-images.githubusercontent.com/20871346/29119613-74490894-7ccc-11e7-9937-f5a7f3a8a89a.png)

Some better request matching may be needed, since the result for `hai` is the planet Hai-home, while the result for `"Hai"` is the government.
I thought I had done this already, but the - character must cause the issue.

Also note that governments often get modified by events, and we have no way to apply events to the government's relationships - only the relationship from the first day of the game can be returned.

**Comment by MCOfficer** [comment]
my bad, i'm dumb :p
