### ISSUE TITLE
-showdata wanderer anti-missile returns the effect, not the outfit

### ISSUE THREAD

**Issue by MCOfficer** [MCOfficer/EndlessSky-Discord-Bot#40]
probably caused by the lower case Name check only Working after spaces, so:

```-lookup world ship``` works, while

```-lookip wanderer anti-missile``` doesn't, cause missile doesn't get recognized as a New word.

**Comment by tehhowch** [comment]
`wanderer anti-missile` is exactly the name of the effect, which is why it gets returned (since a pre-capitalization lookup occurs first). If the command is `-lookup Wanderer anti-missile`, with #41 the outfit info is returned.
We can't really do much other than disable the returning of `effect` data to make the outfit return first when no capitalization is used in the input command.

**Comment by MCOfficer** [comment]
hm. is there a way to prioritize Outfits and ships over effects over systems and planets?
i'll leave this open for now, maybe we can up with something like that.

**Comment by tehhowch** [comment]
We could if we first check both the input and capitalized version with a
reduced search space (e.g. only ships and outfits), and then check both
with the current full search space.
