### ISSUE TITLE
Allow James to save playlists

### ISSUE THREAD

**Issue by warp-core** [MCOfficer/EndlessSky-Discord-Bot#56]
Can we get functionality to James to save a queue so it can be played at a later time without having to add each song one by one?

**Comment by MCOfficer** [comment]
i'll have to look into it, but i'm confident there is a way to do this.

although the same functionality already exists with YouTube/soundcloud playlists.

also, i'm not sure how this should be handled. probably a -save command that saves the queue + the current song. suggestions welcome.

**Comment by 1010todd** [comment]
Here is my suggestion, I think it should be like -createplaylist <playlistname> then -addsong <songname> <playlistname> and -playplaylist <playlistname> to play and -playlist to check what playlist you can play(like -memelist).

**Comment by MCOfficer** [comment]
will this be user-restricted? e.g. if i create a playlist, only i can edit it?
for now, you can still use soundcloud and youtube playlist, wich should work just as well.

**Comment by 1010todd** [comment]
Maybe let the user choose if others can add a song to his/her playlist or not. 
I don't have any programming experience so I don't know if it's too hard.

**Comment by MCOfficer** [comment]
it's not complicated, but will take some time. i don't see many advantages over just making a youtube playlist, so i will probably make this low-priority.

**Comment by Wrzlprnft** [comment]
i'd recommend sticking to youtube or soundcloud playlists.
i'd rather suggest the option to add a pair of keyword and playlist
"-linkadd myplaylist playlistlink" -> saves key and link -> "-play myplaylist" -> queues the link(list)
so, people can add their own playlist for quick usage, but edit the playlist on the medium they chose, because text command based playlist editing would be horrid.
further, one could add some default playlists for genres.

**Comment by MCOfficer** [comment]
should i also add the ability to save the current state of playlists? e.g. when you already played the first tracks, they will not be saved. 
reason is, i saw @warp-core leaving the bot on pause over night (might be the cause of #57 btw), which would be solved by this.

**Comment by tehhowch** [comment]
you'd need a per user storage of the last time they heard each playlist, because person x could play person y's playlist after y leaves.

**Comment by MCOfficer** [comment]
the feature suggested by @Wrzlprnft is done with 415d7951a8c6694d50a91900c6b267f82701190.

the approach on the "save queue" functionality will be as follows:
james will be able to print out the current queue to a text file and send that, with 1 track url per line. think of these as cassettes. whenever you feel like it, you can use `-play [attached file]` to queue all songs from a text file.
this way, users just save playlists on their pc, instead of us having to make a difficult property/permission system around the playlists.

**Comment by MCOfficer** [comment]
8415d7951a8c6694d50a91900c6b267f82701190 and 74955240a1bd1f3863869b87e767ab181b6b3cc0

**Comment by MCOfficer** [comment]
15cc78bbafb4deb8cef219c290a6be06d9277c46 for queue printing

a82fa5fd19b61eda2df797b9c3db10be286fb225 for file inputs
